package com.yuwei.volte.db.dao;

import com.yuwei.volte.db.domain.CallMeasure;
import com.yuwei.volte.db.domain.CallMeasureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallMeasureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    long countByExample(CallMeasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int deleteByExample(CallMeasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int insert(CallMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int insertSelective(CallMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    List<CallMeasure> selectByExample(CallMeasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CallMeasure> selectByExampleSelective(@Param("example") CallMeasureExample example, @Param("selective") CallMeasure.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    CallMeasure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallMeasure selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CallMeasure.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") CallMeasure record, @Param("example") CallMeasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int updateByExample(@Param("record") CallMeasure record, @Param("example") CallMeasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int updateByPrimaryKeySelective(CallMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    int updateByPrimaryKey(CallMeasure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallMeasure selectOneByExample(CallMeasureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallMeasure selectOneByExampleSelective(@Param("example") CallMeasureExample example, @Param("selective") CallMeasure.Column ... selective);
}