package com.yuwei.volte.db.domain;

import java.util.Date;

public class AppInfo extends AppInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.appname
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private String appname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.serverflag
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private String serverflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.lastforce
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private String lastforce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.updateurl
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private String updateurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.upgradeinfo
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private String upgradeinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.addtime
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_info.remark
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.appname
     *
     * @return the value of app_info.appname
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.appname
     *
     * @param appname the value for app_info.appname
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.serverflag
     *
     * @return the value of app_info.serverflag
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public String getServerflag() {
        return serverflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.serverflag
     *
     * @param serverflag the value for app_info.serverflag
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setServerflag(String serverflag) {
        this.serverflag = serverflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.lastforce
     *
     * @return the value of app_info.lastforce
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public String getLastforce() {
        return lastforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.lastforce
     *
     * @param lastforce the value for app_info.lastforce
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setLastforce(String lastforce) {
        this.lastforce = lastforce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.updateurl
     *
     * @return the value of app_info.updateurl
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public String getUpdateurl() {
        return updateurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.updateurl
     *
     * @param updateurl the value for app_info.updateurl
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setUpdateurl(String updateurl) {
        this.updateurl = updateurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.upgradeinfo
     *
     * @return the value of app_info.upgradeinfo
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public String getUpgradeinfo() {
        return upgradeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.upgradeinfo
     *
     * @param upgradeinfo the value for app_info.upgradeinfo
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setUpgradeinfo(String upgradeinfo) {
        this.upgradeinfo = upgradeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.addtime
     *
     * @return the value of app_info.addtime
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.addtime
     *
     * @param addtime the value for app_info.addtime
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_info.remark
     *
     * @return the value of app_info.remark
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_info.remark
     *
     * @param remark the value for app_info.remark
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appname=").append(appname);
        sb.append(", serverflag=").append(serverflag);
        sb.append(", lastforce=").append(lastforce);
        sb.append(", updateurl=").append(updateurl);
        sb.append(", upgradeinfo=").append(upgradeinfo);
        sb.append(", addtime=").append(addtime);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppInfo other = (AppInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getServerversion() == null ? other.getServerversion() == null : this.getServerversion().equals(other.getServerversion()))
            && (this.getAppname() == null ? other.getAppname() == null : this.getAppname().equals(other.getAppname()))
            && (this.getServerflag() == null ? other.getServerflag() == null : this.getServerflag().equals(other.getServerflag()))
            && (this.getLastforce() == null ? other.getLastforce() == null : this.getLastforce().equals(other.getLastforce()))
            && (this.getUpdateurl() == null ? other.getUpdateurl() == null : this.getUpdateurl().equals(other.getUpdateurl()))
            && (this.getUpgradeinfo() == null ? other.getUpgradeinfo() == null : this.getUpgradeinfo().equals(other.getUpgradeinfo()))
            && (this.getAddtime() == null ? other.getAddtime() == null : this.getAddtime().equals(other.getAddtime()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_info
     *
     * @mbg.generated Fri May 24 19:49:41 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getServerversion() == null) ? 0 : getServerversion().hashCode());
        result = prime * result + ((getAppname() == null) ? 0 : getAppname().hashCode());
        result = prime * result + ((getServerflag() == null) ? 0 : getServerflag().hashCode());
        result = prime * result + ((getLastforce() == null) ? 0 : getLastforce().hashCode());
        result = prime * result + ((getUpdateurl() == null) ? 0 : getUpdateurl().hashCode());
        result = prime * result + ((getUpgradeinfo() == null) ? 0 : getUpgradeinfo().hashCode());
        result = prime * result + ((getAddtime() == null) ? 0 : getAddtime().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table app_info
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        serverversion("serverversion"),
        appname("appname"),
        serverflag("serverflag"),
        lastforce("lastforce"),
        updateurl("updateurl"),
        upgradeinfo("upgradeinfo"),
        addtime("addtime"),
        remark("remark");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table app_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table app_info
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}