package com.yuwei.volte.db.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CallMeasureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:01 CST 2019
     */
    public CallMeasureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CallMeasureExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CallMeasureExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CallMeasureExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CallMeasureExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public CallMeasureExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCpnIsNull() {
            addCriterion("cpn is null");
            return (Criteria) this;
        }

        public Criteria andCpnIsNotNull() {
            addCriterion("cpn is not null");
            return (Criteria) this;
        }

        public Criteria andCpnEqualTo(String value) {
            addCriterion("cpn =", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnNotEqualTo(String value) {
            addCriterion("cpn <>", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnGreaterThan(String value) {
            addCriterion("cpn >", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnGreaterThanOrEqualTo(String value) {
            addCriterion("cpn >=", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnLessThan(String value) {
            addCriterion("cpn <", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnLessThanOrEqualTo(String value) {
            addCriterion("cpn <=", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnLike(String value) {
            addCriterion("cpn like", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnNotLike(String value) {
            addCriterion("cpn not like", value, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnIn(List<String> values) {
            addCriterion("cpn in", values, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnNotIn(List<String> values) {
            addCriterion("cpn not in", values, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnBetween(String value1, String value2) {
            addCriterion("cpn between", value1, value2, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnNotBetween(String value1, String value2) {
            addCriterion("cpn not between", value1, value2, "cpn");
            return (Criteria) this;
        }

        public Criteria andCpnlocationIsNull() {
            addCriterion("cpnlocation is null");
            return (Criteria) this;
        }

        public Criteria andCpnlocationIsNotNull() {
            addCriterion("cpnlocation is not null");
            return (Criteria) this;
        }

        public Criteria andCpnlocationEqualTo(String value) {
            addCriterion("cpnlocation =", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationNotEqualTo(String value) {
            addCriterion("cpnlocation <>", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationGreaterThan(String value) {
            addCriterion("cpnlocation >", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationGreaterThanOrEqualTo(String value) {
            addCriterion("cpnlocation >=", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationLessThan(String value) {
            addCriterion("cpnlocation <", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationLessThanOrEqualTo(String value) {
            addCriterion("cpnlocation <=", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationLike(String value) {
            addCriterion("cpnlocation like", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationNotLike(String value) {
            addCriterion("cpnlocation not like", value, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationIn(List<String> values) {
            addCriterion("cpnlocation in", values, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationNotIn(List<String> values) {
            addCriterion("cpnlocation not in", values, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationBetween(String value1, String value2) {
            addCriterion("cpnlocation between", value1, value2, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlocationNotBetween(String value1, String value2) {
            addCriterion("cpnlocation not between", value1, value2, "cpnlocation");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeIsNull() {
            addCriterion("cpnlongitude is null");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeIsNotNull() {
            addCriterion("cpnlongitude is not null");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeEqualTo(String value) {
            addCriterion("cpnlongitude =", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeNotEqualTo(String value) {
            addCriterion("cpnlongitude <>", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeGreaterThan(String value) {
            addCriterion("cpnlongitude >", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("cpnlongitude >=", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeLessThan(String value) {
            addCriterion("cpnlongitude <", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeLessThanOrEqualTo(String value) {
            addCriterion("cpnlongitude <=", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeLike(String value) {
            addCriterion("cpnlongitude like", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeNotLike(String value) {
            addCriterion("cpnlongitude not like", value, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeIn(List<String> values) {
            addCriterion("cpnlongitude in", values, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeNotIn(List<String> values) {
            addCriterion("cpnlongitude not in", values, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeBetween(String value1, String value2) {
            addCriterion("cpnlongitude between", value1, value2, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlongitudeNotBetween(String value1, String value2) {
            addCriterion("cpnlongitude not between", value1, value2, "cpnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeIsNull() {
            addCriterion("cpnlatitude is null");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeIsNotNull() {
            addCriterion("cpnlatitude is not null");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeEqualTo(String value) {
            addCriterion("cpnlatitude =", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeNotEqualTo(String value) {
            addCriterion("cpnlatitude <>", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeGreaterThan(String value) {
            addCriterion("cpnlatitude >", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("cpnlatitude >=", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeLessThan(String value) {
            addCriterion("cpnlatitude <", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeLessThanOrEqualTo(String value) {
            addCriterion("cpnlatitude <=", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeLike(String value) {
            addCriterion("cpnlatitude like", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeNotLike(String value) {
            addCriterion("cpnlatitude not like", value, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeIn(List<String> values) {
            addCriterion("cpnlatitude in", values, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeNotIn(List<String> values) {
            addCriterion("cpnlatitude not in", values, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeBetween(String value1, String value2) {
            addCriterion("cpnlatitude between", value1, value2, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnlatitudeNotBetween(String value1, String value2) {
            addCriterion("cpnlatitude not between", value1, value2, "cpnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathIsNull() {
            addCriterion("cpnrecordpath is null");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathIsNotNull() {
            addCriterion("cpnrecordpath is not null");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathEqualTo(String value) {
            addCriterion("cpnrecordpath =", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathNotEqualTo(String value) {
            addCriterion("cpnrecordpath <>", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathGreaterThan(String value) {
            addCriterion("cpnrecordpath >", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathGreaterThanOrEqualTo(String value) {
            addCriterion("cpnrecordpath >=", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathLessThan(String value) {
            addCriterion("cpnrecordpath <", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathLessThanOrEqualTo(String value) {
            addCriterion("cpnrecordpath <=", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathLike(String value) {
            addCriterion("cpnrecordpath like", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathNotLike(String value) {
            addCriterion("cpnrecordpath not like", value, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathIn(List<String> values) {
            addCriterion("cpnrecordpath in", values, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathNotIn(List<String> values) {
            addCriterion("cpnrecordpath not in", values, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathBetween(String value1, String value2) {
            addCriterion("cpnrecordpath between", value1, value2, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnrecordpathNotBetween(String value1, String value2) {
            addCriterion("cpnrecordpath not between", value1, value2, "cpnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpnremarkIsNull() {
            addCriterion("cpnremark is null");
            return (Criteria) this;
        }

        public Criteria andCpnremarkIsNotNull() {
            addCriterion("cpnremark is not null");
            return (Criteria) this;
        }

        public Criteria andCpnremarkEqualTo(String value) {
            addCriterion("cpnremark =", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkNotEqualTo(String value) {
            addCriterion("cpnremark <>", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkGreaterThan(String value) {
            addCriterion("cpnremark >", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkGreaterThanOrEqualTo(String value) {
            addCriterion("cpnremark >=", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkLessThan(String value) {
            addCriterion("cpnremark <", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkLessThanOrEqualTo(String value) {
            addCriterion("cpnremark <=", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkLike(String value) {
            addCriterion("cpnremark like", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkNotLike(String value) {
            addCriterion("cpnremark not like", value, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkIn(List<String> values) {
            addCriterion("cpnremark in", values, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkNotIn(List<String> values) {
            addCriterion("cpnremark not in", values, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkBetween(String value1, String value2) {
            addCriterion("cpnremark between", value1, value2, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpnremarkNotBetween(String value1, String value2) {
            addCriterion("cpnremark not between", value1, value2, "cpnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnIsNull() {
            addCriterion("cpdn is null");
            return (Criteria) this;
        }

        public Criteria andCpdnIsNotNull() {
            addCriterion("cpdn is not null");
            return (Criteria) this;
        }

        public Criteria andCpdnEqualTo(String value) {
            addCriterion("cpdn =", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnNotEqualTo(String value) {
            addCriterion("cpdn <>", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnGreaterThan(String value) {
            addCriterion("cpdn >", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnGreaterThanOrEqualTo(String value) {
            addCriterion("cpdn >=", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnLessThan(String value) {
            addCriterion("cpdn <", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnLessThanOrEqualTo(String value) {
            addCriterion("cpdn <=", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnLike(String value) {
            addCriterion("cpdn like", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnNotLike(String value) {
            addCriterion("cpdn not like", value, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnIn(List<String> values) {
            addCriterion("cpdn in", values, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnNotIn(List<String> values) {
            addCriterion("cpdn not in", values, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnBetween(String value1, String value2) {
            addCriterion("cpdn between", value1, value2, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnNotBetween(String value1, String value2) {
            addCriterion("cpdn not between", value1, value2, "cpdn");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationIsNull() {
            addCriterion("cpdnlocation is null");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationIsNotNull() {
            addCriterion("cpdnlocation is not null");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationEqualTo(String value) {
            addCriterion("cpdnlocation =", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationNotEqualTo(String value) {
            addCriterion("cpdnlocation <>", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationGreaterThan(String value) {
            addCriterion("cpdnlocation >", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationGreaterThanOrEqualTo(String value) {
            addCriterion("cpdnlocation >=", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationLessThan(String value) {
            addCriterion("cpdnlocation <", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationLessThanOrEqualTo(String value) {
            addCriterion("cpdnlocation <=", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationLike(String value) {
            addCriterion("cpdnlocation like", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationNotLike(String value) {
            addCriterion("cpdnlocation not like", value, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationIn(List<String> values) {
            addCriterion("cpdnlocation in", values, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationNotIn(List<String> values) {
            addCriterion("cpdnlocation not in", values, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationBetween(String value1, String value2) {
            addCriterion("cpdnlocation between", value1, value2, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlocationNotBetween(String value1, String value2) {
            addCriterion("cpdnlocation not between", value1, value2, "cpdnlocation");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeIsNull() {
            addCriterion("cpdnlongitude is null");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeIsNotNull() {
            addCriterion("cpdnlongitude is not null");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeEqualTo(String value) {
            addCriterion("cpdnlongitude =", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeNotEqualTo(String value) {
            addCriterion("cpdnlongitude <>", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeGreaterThan(String value) {
            addCriterion("cpdnlongitude >", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("cpdnlongitude >=", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeLessThan(String value) {
            addCriterion("cpdnlongitude <", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeLessThanOrEqualTo(String value) {
            addCriterion("cpdnlongitude <=", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeLike(String value) {
            addCriterion("cpdnlongitude like", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeNotLike(String value) {
            addCriterion("cpdnlongitude not like", value, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeIn(List<String> values) {
            addCriterion("cpdnlongitude in", values, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeNotIn(List<String> values) {
            addCriterion("cpdnlongitude not in", values, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeBetween(String value1, String value2) {
            addCriterion("cpdnlongitude between", value1, value2, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlongitudeNotBetween(String value1, String value2) {
            addCriterion("cpdnlongitude not between", value1, value2, "cpdnlongitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeIsNull() {
            addCriterion("cpdnlatitude is null");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeIsNotNull() {
            addCriterion("cpdnlatitude is not null");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeEqualTo(String value) {
            addCriterion("cpdnlatitude =", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeNotEqualTo(String value) {
            addCriterion("cpdnlatitude <>", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeGreaterThan(String value) {
            addCriterion("cpdnlatitude >", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("cpdnlatitude >=", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeLessThan(String value) {
            addCriterion("cpdnlatitude <", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeLessThanOrEqualTo(String value) {
            addCriterion("cpdnlatitude <=", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeLike(String value) {
            addCriterion("cpdnlatitude like", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeNotLike(String value) {
            addCriterion("cpdnlatitude not like", value, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeIn(List<String> values) {
            addCriterion("cpdnlatitude in", values, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeNotIn(List<String> values) {
            addCriterion("cpdnlatitude not in", values, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeBetween(String value1, String value2) {
            addCriterion("cpdnlatitude between", value1, value2, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnlatitudeNotBetween(String value1, String value2) {
            addCriterion("cpdnlatitude not between", value1, value2, "cpdnlatitude");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathIsNull() {
            addCriterion("cpdnrecordpath is null");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathIsNotNull() {
            addCriterion("cpdnrecordpath is not null");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathEqualTo(String value) {
            addCriterion("cpdnrecordpath =", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathNotEqualTo(String value) {
            addCriterion("cpdnrecordpath <>", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathGreaterThan(String value) {
            addCriterion("cpdnrecordpath >", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathGreaterThanOrEqualTo(String value) {
            addCriterion("cpdnrecordpath >=", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathLessThan(String value) {
            addCriterion("cpdnrecordpath <", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathLessThanOrEqualTo(String value) {
            addCriterion("cpdnrecordpath <=", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathLike(String value) {
            addCriterion("cpdnrecordpath like", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathNotLike(String value) {
            addCriterion("cpdnrecordpath not like", value, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathIn(List<String> values) {
            addCriterion("cpdnrecordpath in", values, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathNotIn(List<String> values) {
            addCriterion("cpdnrecordpath not in", values, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathBetween(String value1, String value2) {
            addCriterion("cpdnrecordpath between", value1, value2, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnrecordpathNotBetween(String value1, String value2) {
            addCriterion("cpdnrecordpath not between", value1, value2, "cpdnrecordpath");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkIsNull() {
            addCriterion("cpdnremark is null");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkIsNotNull() {
            addCriterion("cpdnremark is not null");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkEqualTo(String value) {
            addCriterion("cpdnremark =", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkNotEqualTo(String value) {
            addCriterion("cpdnremark <>", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkGreaterThan(String value) {
            addCriterion("cpdnremark >", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkGreaterThanOrEqualTo(String value) {
            addCriterion("cpdnremark >=", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkLessThan(String value) {
            addCriterion("cpdnremark <", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkLessThanOrEqualTo(String value) {
            addCriterion("cpdnremark <=", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkLike(String value) {
            addCriterion("cpdnremark like", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkNotLike(String value) {
            addCriterion("cpdnremark not like", value, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkIn(List<String> values) {
            addCriterion("cpdnremark in", values, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkNotIn(List<String> values) {
            addCriterion("cpdnremark not in", values, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkBetween(String value1, String value2) {
            addCriterion("cpdnremark between", value1, value2, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCpdnremarkNotBetween(String value1, String value2) {
            addCriterion("cpdnremark not between", value1, value2, "cpdnremark");
            return (Criteria) this;
        }

        public Criteria andCalltimeIsNull() {
            addCriterion("calltime is null");
            return (Criteria) this;
        }

        public Criteria andCalltimeIsNotNull() {
            addCriterion("calltime is not null");
            return (Criteria) this;
        }

        public Criteria andCalltimeEqualTo(Date value) {
            addCriterion("calltime =", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeNotEqualTo(Date value) {
            addCriterion("calltime <>", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeGreaterThan(Date value) {
            addCriterion("calltime >", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeGreaterThanOrEqualTo(Date value) {
            addCriterion("calltime >=", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeLessThan(Date value) {
            addCriterion("calltime <", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeLessThanOrEqualTo(Date value) {
            addCriterion("calltime <=", value, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeIn(List<Date> values) {
            addCriterion("calltime in", values, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeNotIn(List<Date> values) {
            addCriterion("calltime not in", values, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeBetween(Date value1, Date value2) {
            addCriterion("calltime between", value1, value2, "calltime");
            return (Criteria) this;
        }

        public Criteria andCalltimeNotBetween(Date value1, Date value2) {
            addCriterion("calltime not between", value1, value2, "calltime");
            return (Criteria) this;
        }

        public Criteria andTestresultIsNull() {
            addCriterion("testresult is null");
            return (Criteria) this;
        }

        public Criteria andTestresultIsNotNull() {
            addCriterion("testresult is not null");
            return (Criteria) this;
        }

        public Criteria andTestresultEqualTo(String value) {
            addCriterion("testresult =", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultNotEqualTo(String value) {
            addCriterion("testresult <>", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultGreaterThan(String value) {
            addCriterion("testresult >", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultGreaterThanOrEqualTo(String value) {
            addCriterion("testresult >=", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultLessThan(String value) {
            addCriterion("testresult <", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultLessThanOrEqualTo(String value) {
            addCriterion("testresult <=", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultLike(String value) {
            addCriterion("testresult like", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultNotLike(String value) {
            addCriterion("testresult not like", value, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultIn(List<String> values) {
            addCriterion("testresult in", values, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultNotIn(List<String> values) {
            addCriterion("testresult not in", values, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultBetween(String value1, String value2) {
            addCriterion("testresult between", value1, value2, "testresult");
            return (Criteria) this;
        }

        public Criteria andTestresultNotBetween(String value1, String value2) {
            addCriterion("testresult not between", value1, value2, "testresult");
            return (Criteria) this;
        }

        public Criteria andUploadtypeIsNull() {
            addCriterion("uploadtype is null");
            return (Criteria) this;
        }

        public Criteria andUploadtypeIsNotNull() {
            addCriterion("uploadtype is not null");
            return (Criteria) this;
        }

        public Criteria andUploadtypeEqualTo(String value) {
            addCriterion("uploadtype =", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeNotEqualTo(String value) {
            addCriterion("uploadtype <>", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeGreaterThan(String value) {
            addCriterion("uploadtype >", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeGreaterThanOrEqualTo(String value) {
            addCriterion("uploadtype >=", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeLessThan(String value) {
            addCriterion("uploadtype <", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeLessThanOrEqualTo(String value) {
            addCriterion("uploadtype <=", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeLike(String value) {
            addCriterion("uploadtype like", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeNotLike(String value) {
            addCriterion("uploadtype not like", value, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeIn(List<String> values) {
            addCriterion("uploadtype in", values, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeNotIn(List<String> values) {
            addCriterion("uploadtype not in", values, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeBetween(String value1, String value2) {
            addCriterion("uploadtype between", value1, value2, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andUploadtypeNotBetween(String value1, String value2) {
            addCriterion("uploadtype not between", value1, value2, "uploadtype");
            return (Criteria) this;
        }

        public Criteria andCalllongIsNull() {
            addCriterion("calllong is null");
            return (Criteria) this;
        }

        public Criteria andCalllongIsNotNull() {
            addCriterion("calllong is not null");
            return (Criteria) this;
        }

        public Criteria andCalllongEqualTo(Integer value) {
            addCriterion("calllong =", value, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongNotEqualTo(Integer value) {
            addCriterion("calllong <>", value, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongGreaterThan(Integer value) {
            addCriterion("calllong >", value, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongGreaterThanOrEqualTo(Integer value) {
            addCriterion("calllong >=", value, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongLessThan(Integer value) {
            addCriterion("calllong <", value, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongLessThanOrEqualTo(Integer value) {
            addCriterion("calllong <=", value, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongIn(List<Integer> values) {
            addCriterion("calllong in", values, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongNotIn(List<Integer> values) {
            addCriterion("calllong not in", values, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongBetween(Integer value1, Integer value2) {
            addCriterion("calllong between", value1, value2, "calllong");
            return (Criteria) this;
        }

        public Criteria andCalllongNotBetween(Integer value1, Integer value2) {
            addCriterion("calllong not between", value1, value2, "calllong");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table call_measure
     *
     * @mbg.generated do_not_delete_during_merge Wed May 29 16:24:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private CallMeasureExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(CallMeasureExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public CallMeasureExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table call_measure
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}