package com.yuwei.volte.db.domain;

import java.util.Date;

public class CallDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.id
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.callid
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private Integer callid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.calltype
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private String calltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.calllong
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private Integer calllong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.recordpath
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private String recordpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.createdate
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_detail.testresult
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    private String testresult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.id
     *
     * @return the value of call_detail.id
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.id
     *
     * @param id the value for call_detail.id
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.callid
     *
     * @return the value of call_detail.callid
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public Integer getCallid() {
        return callid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.callid
     *
     * @param callid the value for call_detail.callid
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setCallid(Integer callid) {
        this.callid = callid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.calltype
     *
     * @return the value of call_detail.calltype
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public String getCalltype() {
        return calltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.calltype
     *
     * @param calltype the value for call_detail.calltype
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setCalltype(String calltype) {
        this.calltype = calltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.calllong
     *
     * @return the value of call_detail.calllong
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public Integer getCalllong() {
        return calllong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.calllong
     *
     * @param calllong the value for call_detail.calllong
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setCalllong(Integer calllong) {
        this.calllong = calllong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.recordpath
     *
     * @return the value of call_detail.recordpath
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public String getRecordpath() {
        return recordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.recordpath
     *
     * @param recordpath the value for call_detail.recordpath
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setRecordpath(String recordpath) {
        this.recordpath = recordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.createdate
     *
     * @return the value of call_detail.createdate
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.createdate
     *
     * @param createdate the value for call_detail.createdate
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_detail.testresult
     *
     * @return the value of call_detail.testresult
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public String getTestresult() {
        return testresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_detail.testresult
     *
     * @param testresult the value for call_detail.testresult
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    public void setTestresult(String testresult) {
        this.testresult = testresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_detail
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", callid=").append(callid);
        sb.append(", calltype=").append(calltype);
        sb.append(", calllong=").append(calllong);
        sb.append(", recordpath=").append(recordpath);
        sb.append(", createdate=").append(createdate);
        sb.append(", testresult=").append(testresult);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_detail
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CallDetail other = (CallDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCallid() == null ? other.getCallid() == null : this.getCallid().equals(other.getCallid()))
            && (this.getCalltype() == null ? other.getCalltype() == null : this.getCalltype().equals(other.getCalltype()))
            && (this.getCalllong() == null ? other.getCalllong() == null : this.getCalllong().equals(other.getCalllong()))
            && (this.getRecordpath() == null ? other.getRecordpath() == null : this.getRecordpath().equals(other.getRecordpath()))
            && (this.getCreatedate() == null ? other.getCreatedate() == null : this.getCreatedate().equals(other.getCreatedate()))
            && (this.getTestresult() == null ? other.getTestresult() == null : this.getTestresult().equals(other.getTestresult()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_detail
     *
     * @mbg.generated Thu Jun 06 17:24:06 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCallid() == null) ? 0 : getCallid().hashCode());
        result = prime * result + ((getCalltype() == null) ? 0 : getCalltype().hashCode());
        result = prime * result + ((getCalllong() == null) ? 0 : getCalllong().hashCode());
        result = prime * result + ((getRecordpath() == null) ? 0 : getRecordpath().hashCode());
        result = prime * result + ((getCreatedate() == null) ? 0 : getCreatedate().hashCode());
        result = prime * result + ((getTestresult() == null) ? 0 : getTestresult().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table call_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        callid("callid"),
        calltype("calltype"),
        calllong("calllong"),
        recordpath("recordpath"),
        createdate("createdate"),
        testresult("testresult");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table call_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_detail
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}