package com.yuwei.volte.db.domain;

import java.util.Date;

public class CallMeasure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.id
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpn
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpnlocation
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpnlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpnlongitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpnlongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpnlatitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpnlatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpnrecordpath
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpnrecordpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpnremark
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpnremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpdn
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpdnlocation
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpdnlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpdnlongitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpdnlongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpdnlatitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpdnlatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpdnrecordpath
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpdnrecordpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.cpdnremark
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String cpdnremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.calltime
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private Date calltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.testresult
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String testresult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.uploadtype
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private String uploadtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column call_measure.calllong
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    private Integer calllong;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.id
     *
     * @return the value of call_measure.id
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.id
     *
     * @param id the value for call_measure.id
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpn
     *
     * @return the value of call_measure.cpn
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpn() {
        return cpn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpn
     *
     * @param cpn the value for call_measure.cpn
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpn(String cpn) {
        this.cpn = cpn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpnlocation
     *
     * @return the value of call_measure.cpnlocation
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpnlocation() {
        return cpnlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpnlocation
     *
     * @param cpnlocation the value for call_measure.cpnlocation
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpnlocation(String cpnlocation) {
        this.cpnlocation = cpnlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpnlongitude
     *
     * @return the value of call_measure.cpnlongitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpnlongitude() {
        return cpnlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpnlongitude
     *
     * @param cpnlongitude the value for call_measure.cpnlongitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpnlongitude(String cpnlongitude) {
        this.cpnlongitude = cpnlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpnlatitude
     *
     * @return the value of call_measure.cpnlatitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpnlatitude() {
        return cpnlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpnlatitude
     *
     * @param cpnlatitude the value for call_measure.cpnlatitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpnlatitude(String cpnlatitude) {
        this.cpnlatitude = cpnlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpnrecordpath
     *
     * @return the value of call_measure.cpnrecordpath
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpnrecordpath() {
        return cpnrecordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpnrecordpath
     *
     * @param cpnrecordpath the value for call_measure.cpnrecordpath
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpnrecordpath(String cpnrecordpath) {
        this.cpnrecordpath = cpnrecordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpnremark
     *
     * @return the value of call_measure.cpnremark
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpnremark() {
        return cpnremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpnremark
     *
     * @param cpnremark the value for call_measure.cpnremark
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpnremark(String cpnremark) {
        this.cpnremark = cpnremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpdn
     *
     * @return the value of call_measure.cpdn
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpdn() {
        return cpdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpdn
     *
     * @param cpdn the value for call_measure.cpdn
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpdn(String cpdn) {
        this.cpdn = cpdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpdnlocation
     *
     * @return the value of call_measure.cpdnlocation
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpdnlocation() {
        return cpdnlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpdnlocation
     *
     * @param cpdnlocation the value for call_measure.cpdnlocation
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpdnlocation(String cpdnlocation) {
        this.cpdnlocation = cpdnlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpdnlongitude
     *
     * @return the value of call_measure.cpdnlongitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpdnlongitude() {
        return cpdnlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpdnlongitude
     *
     * @param cpdnlongitude the value for call_measure.cpdnlongitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpdnlongitude(String cpdnlongitude) {
        this.cpdnlongitude = cpdnlongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpdnlatitude
     *
     * @return the value of call_measure.cpdnlatitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpdnlatitude() {
        return cpdnlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpdnlatitude
     *
     * @param cpdnlatitude the value for call_measure.cpdnlatitude
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpdnlatitude(String cpdnlatitude) {
        this.cpdnlatitude = cpdnlatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpdnrecordpath
     *
     * @return the value of call_measure.cpdnrecordpath
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpdnrecordpath() {
        return cpdnrecordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpdnrecordpath
     *
     * @param cpdnrecordpath the value for call_measure.cpdnrecordpath
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpdnrecordpath(String cpdnrecordpath) {
        this.cpdnrecordpath = cpdnrecordpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.cpdnremark
     *
     * @return the value of call_measure.cpdnremark
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getCpdnremark() {
        return cpdnremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.cpdnremark
     *
     * @param cpdnremark the value for call_measure.cpdnremark
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCpdnremark(String cpdnremark) {
        this.cpdnremark = cpdnremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.calltime
     *
     * @return the value of call_measure.calltime
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public Date getCalltime() {
        return calltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.calltime
     *
     * @param calltime the value for call_measure.calltime
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCalltime(Date calltime) {
        this.calltime = calltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.testresult
     *
     * @return the value of call_measure.testresult
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getTestresult() {
        return testresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.testresult
     *
     * @param testresult the value for call_measure.testresult
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setTestresult(String testresult) {
        this.testresult = testresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.uploadtype
     *
     * @return the value of call_measure.uploadtype
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public String getUploadtype() {
        return uploadtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.uploadtype
     *
     * @param uploadtype the value for call_measure.uploadtype
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setUploadtype(String uploadtype) {
        this.uploadtype = uploadtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column call_measure.calllong
     *
     * @return the value of call_measure.calllong
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public Integer getCalllong() {
        return calllong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column call_measure.calllong
     *
     * @param calllong the value for call_measure.calllong
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    public void setCalllong(Integer calllong) {
        this.calllong = calllong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cpn=").append(cpn);
        sb.append(", cpnlocation=").append(cpnlocation);
        sb.append(", cpnlongitude=").append(cpnlongitude);
        sb.append(", cpnlatitude=").append(cpnlatitude);
        sb.append(", cpnrecordpath=").append(cpnrecordpath);
        sb.append(", cpnremark=").append(cpnremark);
        sb.append(", cpdn=").append(cpdn);
        sb.append(", cpdnlocation=").append(cpdnlocation);
        sb.append(", cpdnlongitude=").append(cpdnlongitude);
        sb.append(", cpdnlatitude=").append(cpdnlatitude);
        sb.append(", cpdnrecordpath=").append(cpdnrecordpath);
        sb.append(", cpdnremark=").append(cpdnremark);
        sb.append(", calltime=").append(calltime);
        sb.append(", testresult=").append(testresult);
        sb.append(", uploadtype=").append(uploadtype);
        sb.append(", calllong=").append(calllong);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CallMeasure other = (CallMeasure) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCpn() == null ? other.getCpn() == null : this.getCpn().equals(other.getCpn()))
            && (this.getCpnlocation() == null ? other.getCpnlocation() == null : this.getCpnlocation().equals(other.getCpnlocation()))
            && (this.getCpnlongitude() == null ? other.getCpnlongitude() == null : this.getCpnlongitude().equals(other.getCpnlongitude()))
            && (this.getCpnlatitude() == null ? other.getCpnlatitude() == null : this.getCpnlatitude().equals(other.getCpnlatitude()))
            && (this.getCpnrecordpath() == null ? other.getCpnrecordpath() == null : this.getCpnrecordpath().equals(other.getCpnrecordpath()))
            && (this.getCpnremark() == null ? other.getCpnremark() == null : this.getCpnremark().equals(other.getCpnremark()))
            && (this.getCpdn() == null ? other.getCpdn() == null : this.getCpdn().equals(other.getCpdn()))
            && (this.getCpdnlocation() == null ? other.getCpdnlocation() == null : this.getCpdnlocation().equals(other.getCpdnlocation()))
            && (this.getCpdnlongitude() == null ? other.getCpdnlongitude() == null : this.getCpdnlongitude().equals(other.getCpdnlongitude()))
            && (this.getCpdnlatitude() == null ? other.getCpdnlatitude() == null : this.getCpdnlatitude().equals(other.getCpdnlatitude()))
            && (this.getCpdnrecordpath() == null ? other.getCpdnrecordpath() == null : this.getCpdnrecordpath().equals(other.getCpdnrecordpath()))
            && (this.getCpdnremark() == null ? other.getCpdnremark() == null : this.getCpdnremark().equals(other.getCpdnremark()))
            && (this.getCalltime() == null ? other.getCalltime() == null : this.getCalltime().equals(other.getCalltime()))
            && (this.getTestresult() == null ? other.getTestresult() == null : this.getTestresult().equals(other.getTestresult()))
            && (this.getUploadtype() == null ? other.getUploadtype() == null : this.getUploadtype().equals(other.getUploadtype()))
            && (this.getCalllong() == null ? other.getCalllong() == null : this.getCalllong().equals(other.getCalllong()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_measure
     *
     * @mbg.generated Wed May 29 16:24:02 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCpn() == null) ? 0 : getCpn().hashCode());
        result = prime * result + ((getCpnlocation() == null) ? 0 : getCpnlocation().hashCode());
        result = prime * result + ((getCpnlongitude() == null) ? 0 : getCpnlongitude().hashCode());
        result = prime * result + ((getCpnlatitude() == null) ? 0 : getCpnlatitude().hashCode());
        result = prime * result + ((getCpnrecordpath() == null) ? 0 : getCpnrecordpath().hashCode());
        result = prime * result + ((getCpnremark() == null) ? 0 : getCpnremark().hashCode());
        result = prime * result + ((getCpdn() == null) ? 0 : getCpdn().hashCode());
        result = prime * result + ((getCpdnlocation() == null) ? 0 : getCpdnlocation().hashCode());
        result = prime * result + ((getCpdnlongitude() == null) ? 0 : getCpdnlongitude().hashCode());
        result = prime * result + ((getCpdnlatitude() == null) ? 0 : getCpdnlatitude().hashCode());
        result = prime * result + ((getCpdnrecordpath() == null) ? 0 : getCpdnrecordpath().hashCode());
        result = prime * result + ((getCpdnremark() == null) ? 0 : getCpdnremark().hashCode());
        result = prime * result + ((getCalltime() == null) ? 0 : getCalltime().hashCode());
        result = prime * result + ((getTestresult() == null) ? 0 : getTestresult().hashCode());
        result = prime * result + ((getUploadtype() == null) ? 0 : getUploadtype().hashCode());
        result = prime * result + ((getCalllong() == null) ? 0 : getCalllong().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table call_measure
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id"),
        cpn("cpn"),
        cpnlocation("cpnlocation"),
        cpnlongitude("cpnlongitude"),
        cpnlatitude("cpnlatitude"),
        cpnrecordpath("cpnrecordpath"),
        cpnremark("cpnremark"),
        cpdn("cpdn"),
        cpdnlocation("cpdnlocation"),
        cpdnlongitude("cpdnlongitude"),
        cpdnlatitude("cpdnlatitude"),
        cpdnrecordpath("cpdnrecordpath"),
        cpdnremark("cpdnremark"),
        calltime("calltime"),
        testresult("testresult"),
        uploadtype("uploadtype"),
        calllong("calllong");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table call_measure
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}